name: ci-deno
on:
  push:
    branches:
      - development
    tags:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-app:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Run tests and coverage
        run: deno task coverage
      - name: Get Lcov report
        run: deno task coverage:lcov
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
