name: ci-deno

on:
  pull_request:
    branches:
      - development

jobs:
  check-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [v1.34, v1.33]
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno test -A tests/*
